# Decrypt the file containing the key
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=cloudbuild/id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=cloud-build-keyring
      - --key=github-key
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Set up git with key and domain.
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv cloudbuild/known_hosts /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    args:
      - clone
      - git@github.com:kkos2/os2display-admin.git
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    dir: 'os2display-admin'
    args:
      - reset
      - --hard
      - $COMMIT_SHA

  # Generate build id
  - name: 'gcr.io/cloud-builders/git'
    dir: 'os2display-admin'
    entrypoint: 'bash'
    args: ["-c", "echo \"${BRANCH_NAME}-$(git rev-list --count ${COMMIT_SHA})\" > ../.BUILD_TAG"]
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: ['-c', 'ls -la']

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: ['-c', 'cat .BUILD_TAG']

  - name: 'gcr.io/cloud-builders/git'
    dir: 'os2display-admin'
    entrypoint: 'bash'
    args: ["-c", "git tag \"$(cat ../.BUILD_TAG)\""]

  - name: 'gcr.io/cloud-builders/git'
    dir: 'os2display-admin'
    args:
      - tag

