name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docker setup
        uses: actions/checkout@v2.0.0
        with:
          repository: kkos2/os2display-docker
          ref: kk-master

      - name: Spin up environment
        run: |
          make clone-admin
          make reset-dev
          echo 'TADA'


