name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docker setup
        uses: actions/checkout@v2.0.0
        with:
          repository: kkos2/os2display-docker
          ref: feature/osd-92-actions

      - name: Setup Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set Credential Helper for Docker
        run: gcloud auth configure-docker --quiet

      - name: Spin up environment
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: |
          make clone-admin
          docker-compose -f docker-compose.common.yml -f docker-compose.development.yml config > docker-compose.yml
          docker-compose up -d
          docker-compose exec -T admin-php bash -c "ls -lah web/bundles"
#          sleep 5
#          docker-compose exec -T admin-php bash -c "export TERM=xterm && wait-for-it -t 60 admin-db:3306 && wait-for-it -t 60 elasticsearch:9200"
#          sleep 5
#          docker-compose exec -T admin-php bash -c "export TERM=xterm /opt/development/scripts/_docker-init-environment.sh"

          echo 'TADA'


