name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docker setup
        uses: actions/checkout@v2.0.0
        with:
          repository: kkos2/os2display-docker
          ref: kk-master
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
